import type { Metadata } from "next";
import "./globals.css";

import { Outfit, Raleway } from "next/font/google";
import React from "react";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});
const raleway = Raleway({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "CCE, IIT Mandi | Centre for Continuing Education",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${raleway.variable} ${outfit.className}`}
      >
        {children}
      </body>
    </html>
  );
}
