export const activities = [
  // Leadership Training
  {
    category: "leadership-training",
    name: "Leadership Training 1",
    details: "Introduction to essential leadership skills and strategies.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "leadership-training",
    name: "Leadership Training 2",
    details: "Exploring advanced communication and team management techniques.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "leadership-training",
    name: "Leadership Training 3",
    details: "Developing emotional intelligence for effective leadership.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "leadership-training",
    name: "Leadership Training 4",
    details: "Strategies for conflict resolution and decision-making.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "leadership-training",
    name: "Leadership Training 5",
    details: "Building resilience and adaptability in leadership roles.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },

  // PM Vishwakarma
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma 1",
    details: "Overview of the PM Vishwakarma program and objectives.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma 2",
    details: "Skill development initiatives under PM Vishwakarma.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma 3",
    details: "Vocational training and certification opportunities.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma 4",
    details: "Empowering artisans and craftsmen through PM Vishwakarma.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma 5",
    details: "Entrepreneurship support for traditional crafts and trades.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },

  // Capacity Building
  {
    category: "capacity-building",
    name: "Capacity Building 1",
    details:
      "Enhancing team skills through targeted capacity-building sessions.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "capacity-building",
    name: "Capacity Building 2",
    details: "Workshops on time management and productivity improvement.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "capacity-building",
    name: "Capacity Building 3",
    details: "Skills development for effective project management.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "capacity-building",
    name: "Capacity Building 4",
    details: "Capacity-building initiatives for organizational growth.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "capacity-building",
    name: "Capacity Building 5",
    details: "Training on innovative thinking and problem-solving.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },

  // Short-Term Courses
  {
    category: "short-term-courses",
    name: "Short-Term Course 1",
    details: "Intensive course on digital marketing basics.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "Short-Term Course 2",
    details: "Introduction to web development fundamentals.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "Short-Term Course 3",
    details: "Hands-on training in data analysis and visualization.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "Short-Term Course 4",
    details: "Fundamentals of graphic design and user experience.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "Short-Term Course 5",
    details: "Basic principles of financial literacy and management.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },

  // Online Courses
  {
    category: "online-courses",
    name: "Minor in Business Analytics",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/minor-in-ba",
    Link2: "https://drive.google.com/file/d/1VZbtfbeowci3u7xdrs2hKZJu_WJxLETU",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "online-courses",
    name: "Minor in Artificial Intelligence and Data Science",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/iit-mandi-ai-ds",
    Link2: "https://drive.google.com/file/d/1VdMt6fXNvdhomEQsC15Yv04tpqYK32L_",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "online-courses",
    name: "Minor in Computer Science Engineering",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/minor-in-cse ",
    Link2: "https://drive.google.com/file/d/1ktfKMV-pdtU3tWtCLrkqfkFAAOcGOgzp",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "online-courses",
    name: "Minor in Cyber Security & Ethical Hacking",
    details: "Online Course",
    Link1:
      "https://drive.google.com/file/d/1hg0hUQxfcxKN6DGZTENbK1YNJBnoW2tn/view?usp=sharing",
    Link2: "#",
    Link1Name: "Poster",
    Link2Name: "",
  },
  {
    category: "online-courses",
    name: "Minor in Embedded Systems",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/minor-in-es",
    Link2:
      "https://drive.google.com/file/d/11bbNfS_r9yVWOzqGqtxDbr2-_qXrKDfq/view?usp=sharing",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "fdps",
    name: "Faculty Development Program 1",
    details:
      "Enhancing leadership qualities through strategic decision-making and problem-solving exercises.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "fdps",
    name: "Faculty Development Program 2",
    details:
      "Exploring innovative teaching methodologies to foster engagement and academic excellence.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "fdps",
    name: "Faculty Development Program 3",
    details:
      "Developing effective communication and collaboration skills for academic growth.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "fdps",
    name: "Faculty Development Program 4",
    details:
      "Leveraging technology in education to enhance learning experiences and student interactions.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "conferences",
    name: "International Research Conference 2025",
    details:
      "A platform for researchers and academicians to present their latest findings and innovations",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "conferences",
    name: "AI & Machine Learning Symposium",
    details:
      "An in-depth discussion on the latest trends, breakthroughs, and challenges in AI and ML",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "conferences",
    name: "Hands-on IoT Workshop",
    details:
      "A practical session focused on developing real-world IoT applications using sensors, and cloud computing.",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "gian-courses",
    name: "Data-based Systems and Control",
    details: `A 5-day residential-course, taught by the Faculty from The Netherlands, Prof. Kanat Camlibel and Dr. Henk van Waarde, affiliated to the University of Groningen. Coordinated by Dr. Tushar Jain, SCEE, IIT Mandi.`,
    Link1:
      "https://www.youtube.com/playlist?list=PLiahwtYFf_dDYq8tlPfHv3rcRyadTG0fq",
    Link2: "#",
    Link1Name: "Youtube Playlist",
    Link2Name: "",
  },
  {
    category: "gian-courses",
    name: "Wetting, Capillarity, and Phase Transitions: Experiments and Simulations.",
    details:
      "An introduction to quantum computing, implications in computing advancements.",
    Link1:
      "https://www.youtube.com/playlist?list=PLiahwtYFf_dCAullXgkyr4NbjLncMDdDQ",
    Link2: "#",
    Link1Name: "Youtube Playlist",
    Link2Name: "",
  },
  {
    category: "nptel-courses",
    name: "Linear Dynamical Systems",
    details: "By Prof. Tushar Jain, SCEE, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/108106164",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "Financial Accounting",
    details: "By Prof. Puran Singh, SOM, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/110106147",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "Carbon Materials and Manufacturing",
    details: "By Prof. Swati Sharma, SMME, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/113106099",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },

  {
    category: "nptel-courses",
    name: "Manufacturing of Turbines (Gas, Steam, Hydro and Wind)",
    details: "By Prof. Sunny Zafar, SMME, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/112106622",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "State Space Approach to Control System Analysis and Design",
    details: "Prof. Akhilanand Pati Tiwari, SCEE, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/108106374",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "Large Applications Practicum",
    details: "Prof. Varun Dutt",
    Link1: "https://nptel.ac.in/courses/106106579",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },

  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "exposure-gateway-day",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
];
