export const activities = [
  // Leadership Training

  {
    category: "leadership-training",
    name: "General Management and Leadership Program for GUVNL",
    details: "Coordinated by Prof. N Ravichandran, IIT Mandi",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  // PM Vishwakarma
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma Programme for Tailor",
    details: "NIL",
    Link1:
      "https://drive.google.com/file/d/1GV1mt1WuGlsskmb3lRfEf4HJuKj3gcJH/view?usp=drive_link",
    Link2: "#",
    Link1Name: "Group Photo",
    Link2Name: "",
  },
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma Programme for Blacksmith",
    details: "NIL",
    Link1:
      "https://drive.google.com/file/d/1OeYpRcIbltToXQQvIWBJhlMfJtban69R/view?usp=drive_link",
    Link2: "#",
    Link1Name: "Group Photo",
    Link2Name: "",
  },
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma Programme for Assistant Hair Dresser",
    details: "NIL",
    Link1:
      "https://drive.google.com/file/d/1yQAjdYoZxH_McXqJNpuh7VZ1IaG4MZsu/view?usp=drive_link",
    Link2: "#",
    Link1Name: "Group Photo",
    Link2Name: "",
  },
  {
    category: "pm-vishwakarma",
    name: "PM Vishwakarma Programme for Carpenter",
    details: "NIL",
    Link1:
      "https://drive.google.com/file/d/16c3f8t7SHP0ydyeLw2AFa1VbMSUYruRL/view?usp=drive_link",
    Link2: "#",
    Link1Name: "Group Photo",
    Link2Name: "",
  },

  {
    category: "short-term-courses",
    name: "HPKVN Certificate Course on Machine Learning {1}",
    details: "24 July 2023 to 23 August 2023; One-month Residential Course",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "HPKVN Certificate Course on Internet of Things (IoT)",
    details:
      "30 October 2023 to 29 November 2023; One-month Residential Course",
    Link1:
      "https://drive.google.com/file/d/1Xmxkuk_tNBZxGD6pn6Wl9NAXkQFrvuap/view?usp=sharing",
    Link2: "#",
    Link1Name: "Valedictory Group Photo",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "HPKVN Certificate Course on Robotics",
    details: "3 July 2023 to 23 August 2023; One-month Residential Course",
    Link1:
      "https://drive.google.com/file/d/1Xmxkuk_tNBZxGD6pn6Wl9NAXkQFrvuap/view?usp=sharing",
    Link2: "#",
    Link1Name: "Valedictory Group Photo",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "HPKVN Certificate Course on Machine Learning {2}",
    details:
      "29 January 2024 to 18 February 2024; One-month Residential Course",
    Link1:
      "https://drive.google.com/file/d/1If0deSA4UUDWTK4lFH5hknkJxnjmPNlX/view?usp=sharing",
    Link2: "#",
    Link1Name: "Valedictory Group Photo",
    Link2Name: "",
  },
  {
    category: "short-term-courses",
    name: "Masterclass on Statistical Data Analytics & Deep Learning",
    details: "23 – 27 June 2025",
    Link1:
      "https://drive.google.com/file/d/1FJSxgLT7KQqiRbGKpTTksIgr5RIYwNg-/view",
    Link2: "#",
    Link1Name: "Poster",
    Link2Name: "",
  },

  // Online Courses
  {
    category: "online-courses",
    name: "Minor in Business Analytics",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/minor-in-ba",
    Link2: "https://drive.google.com/file/d/1VZbtfbeowci3u7xdrs2hKZJu_WJxLETU",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "online-courses",
    name: "Minor in Artificial Intelligence and Data Science",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/iit-mandi-ai-ds",
    Link2: "https://drive.google.com/file/d/1VdMt6fXNvdhomEQsC15Yv04tpqYK32L_",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "online-courses",
    name: "Minor in Computer Science Engineering",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/minor-in-cse ",
    Link2: "https://drive.google.com/file/d/1ktfKMV-pdtU3tWtCLrkqfkFAAOcGOgzp",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "online-courses",
    name: "Minor in Cyber Security & Ethical Hacking",
    details: "Online Course",
    Link1:
      "https://drive.google.com/file/d/1hg0hUQxfcxKN6DGZTENbK1YNJBnoW2tn/view?usp=sharing",
    Link2: "#",
    Link1Name: "Poster",
    Link2Name: "",
  },
  {
    category: "online-courses",
    name: "Minor in Embedded Systems",
    details: "Online Course",
    Link1: "https://cce.iitmandi.ac.in/minor-in-es",
    Link2:
      "https://drive.google.com/file/d/11bbNfS_r9yVWOzqGqtxDbr2-_qXrKDfq/view?usp=sharing",
    Link1Name: "Website",
    Link2Name: "Poster",
  },
  {
    category: "fdps",
    name: "SCERT Delhi - FDP for PGT Biology",
    details: "NIL",
    Link1:
      "https://drive.google.com/file/d/1_GsXSrSHNRjpzN_1Pmk6diiNJUh0QGDg/view?usp=sharing",
    Link2: "#",
    Link1Name: "Valedictory Group Photo",
    Link2Name: "",
  },
  {
    category: "fdps",
    name: "SCERT Delhi - FDP for PGT Chemistry",
    details: "NIL",
    Link1:
      "https://drive.google.com/file/d/1vuN89QUFAehRHSOcXKfyYlKYT5pSMbnf/view?usp=sharing",
    Link2: "#",
    Link1Name: "Valedictory Group Photo",
    Link2Name: "",
  },
  {
    category: "fdps",
    name: "SCERT Delhi - FDP for PGT Mathematics",
    details: "NIL",
    Link1:
      "https://drive.google.com/file/d/1CGQ0y3HsNFAnBbDH7VEi6v_QLvpIujNO/view?usp=sharing",
    Link2: "#",
    Link1Name: "Valedictory Group Photo",
    Link2Name: "",
  },
  {
    category: "fdps",
    name: "SCERT Delhi - FDP for PGT Physics",
    details: "NIL",
    Link1: "",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "conferences",
    name: "A Hands-on Workshop on Composites Design and Manufacturing",
    details: "16 June to 20 June 2025",
    Link1:
      "https://research.iitmandi.ac.in/cdpmhm2025/doc/5D%20CDM%20HW%202025%20Brochure.pdf",
    Link2: "#",
    Link1Name: "Brochure",
    Link2Name: "",
  },
  {
    category: "gian-courses",
    name: "Data-based Systems and Control",
    details: `A 5-day residential-course, taught by the Faculty from The Netherlands, Prof. Kanat Camlibel and Dr. Henk van Waarde, affiliated to the University of Groningen. Coordinated by Dr. Tushar Jain, SCEE, IIT Mandi.`,
    Link1:
      "https://www.youtube.com/playlist?list=PLiahwtYFf_dDYq8tlPfHv3rcRyadTG0fq",
    Link2: "#",
    Link1Name: "Youtube Playlist",
    Link2Name: "",
  },
  {
    category: "gian-courses",
    name: "Wetting, Capillarity, and Phase Transitions: Experiments and Simulations.",
    details:
      "An introduction to quantum computing, implications in computing advancements.",
    Link1:
      "https://www.youtube.com/playlist?list=PLiahwtYFf_dCAullXgkyr4NbjLncMDdDQ",
    Link2: "#",
    Link1Name: "Youtube Playlist",
    Link2Name: "",
  },
  {
    category: "nptel-courses",
    name: "Linear Dynamical Systems",
    details: "By Prof. Tushar Jain, SCEE, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/108106164",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "Financial Accounting",
    details: "By Prof. Puran Singh, SOM, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/110106147",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "Carbon Materials and Manufacturing",
    details: "By Prof. Swati Sharma, SMME, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/113106099",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },

  {
    category: "nptel-courses",
    name: "Manufacturing of Turbines (Gas, Steam, Hydro and Wind)",
    details: "By Prof. Sunny Zafar, SMME, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/112106622",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "State Space Approach to Control System Analysis and Design",
    details: "Prof. Akhilanand Pati Tiwari, SCEE, IIT Mandi",
    Link1: "https://nptel.ac.in/courses/108106374",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },
  {
    category: "nptel-courses",
    name: "Large Applications Practicum",
    details: "Prof. Varun Dutt",
    Link1: "https://nptel.ac.in/courses/106106579",
    Link2: "https://www.youtube.com/@cce-iitmandi/playlists",
    Link1Name: "Course Page",
    Link2Name: "Youtube Playlist",
  },

  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "msme-courses",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
  {
    category: "exposure-gateway-day",
    name: "Heading",
    details: "Content Here",
    Link1: "#",
    Link2: "#",
    Link1Name: "",
    Link2Name: "",
  },
];
